name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ui-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # - name: Update visual snapshots
      #   run: npx playwright test tests/ui/visual --update-snapshots
      # - name: Upload updated snapshots
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: updated-snapshots
      #     path: tests/ui/visual/**/*.png

      - name: Run UI tests
        run: npx playwright test --project=setup-chromium --project=setup-firefox --project=setup-webkit --project=chromium --project=firefox --project=webkit --project=chromium-unauthenticated --project=mobile-chrome --project=mobile-safari
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-ui
          path: playwright-report/
          retention-days: 30

  api-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Cache Playwright browsers
        id: playwright-cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run API tests
        run: npx playwright test --project=api
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-ui
          path: playwright-report/
          retention-days: 30
